name: CI
on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Build for production
        run: npm run build
      - name: Release
        run: npm run release
