name: CI
on:
  push:
    branches:
      - master
      - next
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare repository
        run: git fetch --unshallow --tags
        
      - name: npm install
        run: npm install
        
      - name: Build for production
        run: npm run build
          
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
